//
//  CharacterName.swift
//  SHFList
//
//  Created by Ronaldo Rendón Loja on 22/1/24.
//

import Foundation

enum CharacterName: String {
    case trunksSSJ = "https://www.figuritasde.com/wp-content/uploads/2020/05/DBZ-Trunks-SSJ.jpg"
    case gokuSSJ = "https://www.figuritasde.com/wp-content/uploads/2020/05/02-DBZ-Goku-SSJ.jpg"
    case piccolo = "https://www.figuritasde.com/wp-content/uploads/2020/05/01-DBZ-Piccolo.jpg"
    case frezeerSecond = "https://tamashiiweb.com/images/item/item_0000014154_PwWk6rhp_05.jpg"
    case turles = "https://tamashiiweb.com/images/item/item_0000014094_KqMef09Y_10.jpg"
    case vegetaSSJ4 = "https://www.figuritasde.com/wp-content/uploads/2022/12/105-DB-GT-Super-Saiyan-4-Vegeta.webp"
    case piccoloOrange = "https://www.figuritasde.com/wp-content/uploads/2023/03/148-DB-Super-Super-Hero-Orange-Piccolo.webp"
    case trunksAboy = "https://tamashiiweb.com/images/item/item_0000014204_UySdaygb_07.jpg"
    case vegetaSSJ = "https://www.figuritasde.com/wp-content/uploads/2022/11/111-DBZ-Super-Saiyan-Vegeta-Awakening-Super-Saiyan-Blood.webp"
    case krillinNamek = "https://tamashiiweb.com/images/item/item_0000013975_EGUEUl2Y_08.jpg"
    case cell = "https://tamashiiweb.com/images/item/item_0000013900_feGUFkDK_06.jpg"
    case booGordo = "https://tamashiiweb.com/images/item/item_0000014162_TnZKuRYe_05.jpg"
    case gohanDBS = "https://www.figuritasde.com/wp-content/uploads/2022/09/101-DB-Super-Super-Hero-Ultimate-Gohan.webp"
    case vegetaDBS = "https://www.figuritasde.com/wp-content/uploads/2022/09/100-DB-Super-Super-Hero-Vegeta.webp"
    case frezzerCuarta = "https://tamashiiweb.com/images/item/item_0000013711_sO2M6My8_01.jpg"
    case krillin = "https://tamashiiweb.com/images/item/item_0000013677_1tBtowz2_04.jpg"
    case gokuSSJ4 = "https://www.figuritasde.com/wp-content/uploads/2021/12/88-DBGT-Super-Saiyan-4-Son-Goku.webp"
    case cooler = "https://www.figuritasde.com/wp-content/uploads/2021/08/86-DBZ-Cooler-Final-Form.webp"
    case gokuBlack = "https://www.figuritasde.com/wp-content/uploads/2021/08/85-DB-Super-Goku-Black-Super-Saiyan-Rose.webp"
    case gokuKawai = "https://tamashiiweb.com/images/item/item_0000013505_WeELih0m_05.jpg"
    case gokuGod = "https://www.figuritasde.com/wp-content/uploads/2021/07/SDCC-2021-DB-Tour-DB-Super-Event-Exclusive-Super-Saiyan-God-Son-Goku.jpg"
    case nappa = "https://www.figuritasde.com/wp-content/uploads/2021/07/SDCC-2021-DB-Tour-DB-Super-Event-Exclusive-Nappa.jpg"
    case frezzerPrimera = "https://tamashiiweb.com/images/item/item_0000013437_jivtUKFK_01.jpg"
    case bardock = "https://tamashiiweb.com/images/item/item_0000013330_F3UnCqCc_04.jpg"
    case roshiChun = "https://www.figuritasde.com/wp-content/uploads/2020/06/64-DB-Jackie-Chun.jpg"
    case taoPaiPai = "https://www.figuritasde.com/wp-content/uploads/2020/06/62-DB-Tao-Pai-Pai.jpg"
    case bulmaKid = "https://www.figuritasde.com/wp-content/uploads/2020/05/DB-Bulma-Adventure-Begins.jpg"
    case gokuBlue = "https://www.figuritasde.com/wp-content/uploads/2020/06/56-DB-Super-Broly-Super-Saiyan-God-Super-Saiyan-Son-Goku.jpg"
    case gogeta = "https://www.figuritasde.com/wp-content/uploads/2020/06/53-DB-Super-Broly-Super-Saiyan-God-Super-Saiyan-Gogeta.jpg"
    case booFlaco = "https://tamashiiweb.com/images/item/item_0000012722_MQMmpLbh_06.jpg"
    case roshi = "https://www.figuritasde.com/wp-content/uploads/2020/06/44-DB-Kame-Sennin.jpg"
    case gokuBase = "https://tamashiiweb.com/images/item/item_0000012445_aihueMIF_07.jpg"
    case gokuKid = "https://www.figuritasde.com/wp-content/uploads/2020/06/39-DB-Kid-Son-Goku.jpg"
    case gokuFrezzer = "https://www.figuritasde.com/wp-content/uploads/2020/06/20-DBZ-Super-Saiyan-Son-Goku-Super-Warrior-Awakening-ver.jpg"
    case gohanTeen = "https://www.figuritasde.com/wp-content/uploads/2020/05/03-DBZ-Goku-SSJ.jpg"
    case broly = "https://www.figuritasde.com/wp-content/uploads/2020/06/52-DB-Super-Broly-Broly-Fullpower.jpg"
    case gokuSSJ3 = "https://tamashiiweb.com/images/item/item_0000012125_JFkRyiBY_01.jpg"
    case granSayaman = "https://www.figuritasde.com/wp-content/uploads/2020/06/50-DBZ-Great-Sayaman.jpg"
    case mrSatan = "https://www.figuritasde.com/wp-content/uploads/2020/06/49-DBZ-Mr.Satan_.jpg"
    case spiderman = "https://tamashiiweb.com/images/item/item_0000014521_Ngc1GRVw_05.jpg"
    case frezzerTercera = "https://tamashiiweb.com/images/item/item_0000014313_SXlT1joQ_05.jpg"
    case android19 = "https://tamashiiweb.com/images/item/item_0000014375_SdH1fNLt_05.jpg"
    case metalCooler = "https://tamashiiweb.com/images/item/item_0000014435_aIEVDH8S_03.jpg"
    case gokuMamado = "https://tamashiiweb.com/images/item/item_0000014415_yQJ2CO2V_09.jpg"
    case gohanSSJ2 = "https://tamashiiweb.com/images/item/item_0000014499_eMkv2R5h_05.jpg"
    case raditzGohan = "https://tamashiiweb.com/images/item/item_0000014500_s6ySCYnp_07.jpg"
    case majinVegeta = "https://tamashiiweb.com/images/item/item_0000014501_1EufMQ61_03.jpg"
    case vegeta24000 = "https://tamashiiweb.com/images/item/item_0000014665_pMykt1NZ_01.jpg"
    // Desde aqui no tengo
    case android21 = "https://www.figuritasde.com/wp-content/uploads/2022/09/DB-Games-Battle-Hour-DB-FighterZ-Android-No.-21-White-Coat-Event-Exclusive-2022.webp"
    case shenron = "https://www.figuritasde.com/wp-content/uploads/2022/09/SDCC-2022-Exclusive-Edition-DBZ-Shenron.webp"
    case brolyMamado = "https://www.figuritasde.com/wp-content/uploads/2022/09/NYCC-2022-Exclusive-Edition-DB-Super-Super-Saiyan-Broly.webp"
    case gokuSSJ2 = "https://www.figuritasde.com/wp-content/uploads/2022/09/SDCC-2022-Exclusive-Edition-DBZ-Super-Saiyan-2-Son-Goku.webp"
    case andoid16 = "https://www.figuritasde.com/wp-content/uploads/2022/09/SDCC-2022-Exclusive-Edition-DBZ-Android-16.webp"
    case gokuSSGSS = "https://www.figuritasde.com/wp-content/uploads/2021/10/NYCC-2021-Event-Exclusive-Color-Edition-DB-Super-SSGSS-Son-Goku-Kaio-Ken.webp"
    case whis = "https://www.figuritasde.com/wp-content/uploads/2021/07/SDCC-2021-DB-Tour-DB-Super-Event-Exclusive-Whis.jpg"
    case beerus = "https://www.figuritasde.com/wp-content/uploads/2021/07/SDCC-2021-DB-Tour-DB-Super-Event-Exclusive-Beerus.jpg"
    case android18 = "https://www.figuritasde.com/wp-content/uploads/2020/07/SDCC-2020-DB-Tour-DBZ-Android-18-Event-Exclusive-Color-Edition-1.jpg"
    case android17 = "https://www.figuritasde.com/wp-content/uploads/2020/07/SDCC-2020-DB-Tour-DBZ-Android-17-Event-Exclusive-Color-Edition-1.jpg"
    case gokuUI = "https://www.figuritasde.com/wp-content/uploads/2020/07/SDCC-2020-DB-Tour-DB-Super-Goku-Sign-UI-Event-Exclusive-Color-Edition-1.jpg"
    case brolyDBZ = "https://www.figuritasde.com/wp-content/uploads/2020/06/SDCC-2018-DB-Tour-DBZ-Broly-Event-Exclusive-Color-Edition.jpg"
    case gohanBestia = "https://www.figuritasde.com/wp-content/uploads/2023/03/146-DB-Super-Super-Hero-Gohan-Beast.webp"
    case brolyDBS = "https://www.figuritasde.com/wp-content/uploads/2022/12/114-DB-Super-Super-Hero-Broly.webp"
    case pan = "https://www.figuritasde.com/wp-content/uploads/2022/11/113-DB-Super-Super-Hero-Pan.webp"
    case gamma2 = "https://www.figuritasde.com/wp-content/uploads/2022/06/107-DB-Super-Super-Hero-Gamma-2.webp"
    case gamma1 = "https://www.figuritasde.com/wp-content/uploads/2022/06/106-DB-Super-Super-Hero-Gamma-1.webp"
    case porunga = "https://www.figuritasde.com/wp-content/uploads/2023/01/108-DBZ-Porunga-Dende-Glowing-Dragon-Ball-Set.webp"
    case kidGohanNamek = "https://www.figuritasde.com/wp-content/uploads/2022/11/103-DBZ-Gohan-Battle-Clothes.webp"
    case zarbon = "https://www.figuritasde.com/wp-content/uploads/2022/12/97-DBZ-Zarbon.webp"
    case dodoria = "https://www.figuritasde.com/wp-content/uploads/2022/12/96-DBZ-Dodoria.webp"
    case kefla = "https://www.figuritasde.com/wp-content/uploads/2022/12/94-DB-Super-Super-Saiyan-Kefla.webp"
    case bulmaNamek = "https://www.figuritasde.com/wp-content/uploads/2021/12/89-DBZ-Bulma-Journey-to-Planet-Namek.webp"
    case tenshinhan = "https://www.figuritasde.com/wp-content/uploads/2021/12/87-DBZ-Tenshinhan-Chaoz.webp"
    case launch = "https://www.figuritasde.com/wp-content/uploads/2021/08/84-DB-Launch.jpg"
    case hit = "https://www.figuritasde.com/wp-content/uploads/2021/08/82-DB-Super-Hit.jpg"
    case burterGuldo = "https://www.figuritasde.com/wp-content/uploads/2021/08/80-DBZ-Burter-y-Guldo.jpg"
    case recoome = "https://www.figuritasde.com/wp-content/uploads/2021/04/77-DBZ-Recoome.jpg"
    case jeice = "https://www.figuritasde.com/wp-content/uploads/2021/02/76-DBZ-Jeice.jpg"
    case zamasu = "https://www.figuritasde.com/wp-content/uploads/2020/11/70-DB-Super-Zamasu.jpg"
    case kidGohan = "https://www.figuritasde.com/wp-content/uploads/2020/12/73-DBZ-Kid-Son-Gohan.jpg"
    case piccoloNamekiano = "https://www.figuritasde.com/wp-content/uploads/2020/12/74-DBZ-Piccolo-The-Pround-Namekian.jpg"
    case vegitoSSGSS = "https://www.figuritasde.com/wp-content/uploads/2020/10/69-DB-Super-SSGSS-Vegito.jpg"
    case jirenMamado = "https://www.figuritasde.com/wp-content/uploads/2020/09/71-DB-Super-Jiren-Final-Battle.jpg"
    case kidChichi = "https://www.figuritasde.com/wp-content/uploads/2020/09/68-DB-Kid-Chi-Chi.jpg"
    case mono = "https://www.figuritasde.com/wp-content/uploads/2020/07/67-DBZ-Great-Ape-Vegeta.jpg"
    case ginyu = "https://www.figuritasde.com/wp-content/uploads/2020/07/66-DBZ-Ginyu.jpg"
    case gokuKaoihken = "https://www.figuritasde.com/wp-content/uploads/2020/07/65-DBZ-Son-Goku-Kaiohken.jpg"
    case jiren = "https://www.figuritasde.com/wp-content/uploads/2020/05/DBS-Jiren.jpg"
    case piccoloDauimaoh = "https://www.figuritasde.com/wp-content/uploads/2020/05/DB-Piccolo-Daimaoh.jpg"
    case brolyArmor = "https://www.figuritasde.com/wp-content/uploads/2020/05/DB-Super-Broly-con-Armadura.jpg"
    case zamasuPotara = "https://www.figuritasde.com/wp-content/uploads/2020/06/57-DB-Super-Zamasu-Potara.jpg"
    case android21Buu = "https://www.figuritasde.com/wp-content/uploads/2020/06/55-DB-FighterZ-Android-21.jpg"
    case kidKrillin = "https://www.figuritasde.com/wp-content/uploads/2020/05/DB-Krillin.jpg"
    case gotenks = "https://www.figuritasde.com/wp-content/uploads/2020/05/DBZ-Gotenks-SSJ.jpg"
    case bulmaCafe = "https://www.figuritasde.com/wp-content/uploads/2020/06/46-DB-Bulma.jpg"
    case yamcha = "https://www.figuritasde.com/wp-content/uploads/2020/06/37-DBZ-Yamcha.jpg"
    case vegetaScooter = "https://www.figuritasde.com/wp-content/uploads/2020/06/32-DBZ-Vegeta-Ver.-2.jpg"
    case cellPremiumColor = "https://www.figuritasde.com/wp-content/uploads/2020/06/29-DBZ-Cell-Premium-Color.jpg"
    case teenGohanDamaged = "https://www.figuritasde.com/wp-content/uploads/2020/06/28-DBZ-Super-Saiyan-Gohan-Battle-Damaged.jpg"
    case broly2014 = "https://www.figuritasde.com/wp-content/uploads/2020/06/14-DBZ-Broly.jpg"
    
}
